[WIP] Add documentation for envisage APIs
enthought/envisage pull request #340
Opened 2020-10-22 21:08 UTC by aaronayres35

fixes #302 

This PR updates the module docstrings of api modules so that their content is documented.

The PR is currently flagged as WIP as I am not sure the best way to organize the classes etc so that the documentation is more clear (specifically in the main `envisage.api` module).  ATM I have a `Interfaces` section and an `Exceptions` section, but I paused because I feel like this approach is not what we want long term.  I imagine we would want to break it up into things like `Plugins`, `ExtensionPoints` and `Services`, or maybe have sections for `Managers` or `Registry`s.  I am not sure, but will update this PR once this is decided on.

2020-10-23 08:15 UTC, rahulporuri requested changes
I'm not sure exactly why but the built documentation is still empty.

2020-10-23 12:38 UTC, aaronayres35 commented
> I'm not sure exactly why but the built documentation is still empty.

When I built it locally I was seeing it.  Very strange, I will investigate

2020-10-23 13:24 UTC, aaronayres35 commented
> > I'm not sure exactly why but the built documentation is still empty.
> 
> When I built it locally I was seeing it. Very strange, I will investigate

I can't seem to reproduce.  @kitchoi if you have the time would you be able to try building the docs and lmk if the api modules are populated?

2020-10-23 13:54 UTC, kitchoi commented
Yep, I can try that.

2020-10-23 14:55 UTC, kitchoi commented
I can also see the populated content for the `api` modules.
This is what I did:
```
$ git checkout doc-302-document-apis
$ python etstool.py install --editable
$ python etstool.py docs
```
Then open `docs/build/index.html` for the main page, and navigate to the corresponding api modules...
e.g.
<img width="670" alt="Screenshot 2020-10-23 at 15 54 26" src="https://user-images.githubusercontent.com/3673984/97019282-0d4e5c80-1548-11eb-80cb-93a8db38f5db.png">

2020-10-26 08:33 UTC, rahulporuri approved these changes
LGTM.

2020-10-26 08:33 UTC, rahulporuri commented on envisage/api.py
> +
```suggestion

Application, plugin and related classes
------------------------------------------
```

2020-10-26 08:33 UTC, rahulporuri commented
> I'm not sure exactly why but the built documentation is still empty.

Sorry about that. I always forget to install the package in editable mode.

2020-10-26 12:48 UTC, merged